### PR TITLE
Added style for invalid inputs  

### PR DESCRIPTION
**Pull request by edmellum**
Added style for invalid inputs. Highly needed as some browsers will not submit a form if an input is invalid.

### CODE REVIEW

**Comment by nathansmith** [comment]
Just wanted to let you know I'm not ignoring this. I just haven't had a time to look into it yet.

**Comment by nathansmith** [comment]
I tried adding this in, but it makes browsers like Chrome highlight things as red, even before the user has had a chance to interact with the page. For instance, an empty text field, with the required attribute, because it has not been filled out, is given a red glow in Chrome when the page loads, but the user hasn't even had a chance to do anything yet.

```
<input type="text" required="required" />
```

So, instead of adding a red glow to all browsers, I have suppressed it for Firefox.

```
:invalid {
  /*
    Suppress red glow that Firefox
    adds to form fields by default,
    even when user is still typing.
  */
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
  box-shadow: none;
}
```

There is still a visual cue via a tooltip. I have styled Chrome's tooltips to look like Firefox native, and will push that code soon.

**Comment by edmellum** [comment]
I'd prefer being able to give the user validation feedback as she's filling the form out, but I guess I could do that with a little extra JS snippet.

**Comment by nathansmith** [comment]
Yeah, I wish that all browsers handled :invalid the same way. Unfortunately, currently, they do things slightly differently, which I think would lead to confusion, if adding a red outline in _all_ browsers to match Firefox.

**Comment by edmellum** [comment]
So I've experimented a bit and found out that I can duplicate Firefox's behavior with JS in every browser thereby ending another annoying cross-browser form-behavior. If I wrote it up in all the JS frameworks Formalize supports, would you consider pulling it?

**Comment by nathansmith** [comment]
With Formalize, I just wanted to cover some of the low-hanging fruit, but not go for a full HTML5 polyfill, since those types of things already exist. I want to wait and see if browsers will eventually settle on how to handle :invalid in a consistent way. I feel like HTML5 is still like the "wild west" and the dust hasn't settled yet, so I don't want to try and make browsers behave the same yet, when they haven't yet made up their minds.

**Pull request closed without merging**
